version: '3.4'

services:
  ore2discourse-auth-gateway:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT: 8000
      HOST: localhost
      BASE_URL: http://localhost:8000
      ORE_URL: http://localhost:9000
      DISCOURSE_URL: http://discourse.example.com
      DISCOURSE_SSO_SECRET: changeme
      DISCOURSE_API_KEY: changeme
      DISCOURSE_API_USER: system
      AUTH_SSO_SECRET: changeme
      AUTH_API_KEY: changeme
